# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
#gem 'faker', '~> 1.9' #nombre de la gema y version
gem 'ruby2d', '~> 0.5.1' 
gem 'minitest', '~>5'

# gem "rails"
